spring:
  application:
      name: springAi
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:30b
      embedding:
        options:
          model: nomic-embed-text
#    openai:
#      api-key: key
#      chat:
#        options:
#          model: gpt-4o-mini
#          temperature: 0.9
#      embedding:
#        options:
#          model: text-embedding-3-small

  datasource:
    url: jdbc:postgresql://localhost:5434/my-vector-db
    username: my-user
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
#    com.zaxxer.hikari: DEBUG
    org.springframework.ai:
     chat.client: DEBUG


